language: java
jdk:
  - openjdk8

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - ./mvnw clean install
  - docker --version # print the version for logging
  - docker build -t simple-express .
  - docker tag simple-express drax7/simple-express:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push drax7/simple-express
