language: java
jdk:
  - openjdk8

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - ./mvnw clean install
  - docker --version # print the version for logging
  - docker build -t travis-demo .
  - docker tag travis-demo thiethaa/travis-demo:v.1.0.0

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thiethaa/travis-demo:v.1.0.0
